version: 2
jobs:
  build:
    working_directory: ~/react-mobiledoc-editor
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - run: yarn install --pure-lockfile
      - run: yarn test
